# Generated by Django 4.0.1 on 2022-01-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
    ]
