# Generated by Django 4.0.1 on 2022-02-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_button',
            field=models.CharField(default='', max_length=255),
        ),
    ]
