# Generated by Django 4.0.1 on 2022-02-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_dislike_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike_button',
            field=models.CharField(default='fa fa-thumbs-down', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_button',
            field=models.CharField(default='fa fa-heart', max_length=255),
        ),
    ]
