# Generated by Django 4.0.1 on 2022-02-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_dislike_button_alter_post_like_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike_button',
            new_name='dislike_button_color',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like_button',
            new_name='like_button_color',
        ),
    ]
