# Generated by Django 4.0.1 on 2022-02-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_rename_dislike_button_post_dislike_button_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike_button_color',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_button_color',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
