# Generated by Django 4.0.1 on 2022-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_post_dislike_button_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike_button_color',
            field=models.CharField(blank=True, default='color:red', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_button_color',
            field=models.CharField(blank=True, default='color:blue', max_length=255, null=True),
        ),
    ]
