# Generated by Django 4.0.1 on 2022-03-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_category_options_post_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
