# Generated by Django 4.0.1 on 2022-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_post_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='downloads/%Y/%m/%d/')),
            ],
        ),
    ]
