# Generated by Django 4.0.1 on 2022-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_downloadfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadfiles',
            options={'verbose_name_plural': 'Download Files'},
        ),
        migrations.AddField(
            model_name='downloadfiles',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
