# Generated by Django 4.0.1 on 2022-03-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_downloadfiles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfiles',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
