# Generated by Django 4.0.1 on 2022-03-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_downloadfiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfiles',
            name='linux',
            field=models.FileField(default='', upload_to='downloads/linux/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='downloadfiles',
            name='windows',
            field=models.FileField(default='', upload_to='downloads/windows/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='downloadfiles',
            name='file',
            field=models.FileField(upload_to='downloads/mobile/%Y/%m/%d/'),
        ),
    ]
