# Generated by Django 4.0.1 on 2022-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_downloadfiles_file_alter_downloadfiles_linux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/mobile/%Y/%m/%d/'),
        ),
    ]
