# Generated by Django 4.0.1 on 2022-04-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/%Y/%m/%d/'),
        ),
    ]
