# Generated by Django 4.0.1 on 2022-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('like_ip', models.BooleanField(verbose_name=False)),
                ('dislike_ip', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
