# Generated by Django 4.0.1 on 2022-04-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_alter_likedislike_dislike_ip_alter_likedislike_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedislike',
            old_name='dislike_ip',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='likedislike',
            old_name='like_ip',
            new_name='like',
        ),
    ]
