# Generated by Django 4.0.1 on 2022-04-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_rename_dislike_ip_likedislike_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='dislike',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
