# Generated by Django 4.0.1 on 2022-04-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_likedislike_dislike_alter_likedislike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disliked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
