# Generated by Django 4.0.1 on 2022-04-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_post_disliked_post_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeDislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
