# Generated by Django 4.0.1 on 2022-06-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_delete_likedislike_remove_post_disliked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadfiles',
            name='total_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
