# Generated by Django 4.0.1 on 2022-07-07 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_downloadfiles_total_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=255)),
                ('checkout_request_id', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], max_length=255)),
                ('receipt_number', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=255)),
            ],
        ),
    ]
